import type { JourneyPhase } from "./types";

// Draft phases built from the resume. Himasri should review the wording; keep the structure.
export const journey: JourneyPhase[] = [
  {
    step: "01",
    title: "Foundations",
    when: "2021 onwards, VIT",
    accent: "blue",
    icon: "code",
    learned: "Programming, data structures, SQL, computer science fundamentals",
    tools: ["Python", "Java", "C/C++", "SQL"],
    built: [{ label: "B.Tech coursework", href: "#about" }],
  },
  {
    step: "02",
    title: "Core ML",
    when: null,
    accent: "green",
    icon: "chart",
    learned: "Supervised learning, model comparison, time-based validation, cost-based thresholds",
    tools: ["scikit-learn", "LightGBM", "XGBoost"],
    built: [{ label: "CardShield", href: "/projects/cardshield" }],
  },
  {
    step: "03",
    title: "Deep learning and NLP",
    when: null,
    accent: "amber",
    icon: "brain",
    learned: "Embeddings, transformers, text extraction",
    tools: ["TensorFlow", "BERT", "KeyBERT"],
    built: [{ label: "Petrofac tender analysis pipeline", href: "#exp-petrofac" }],
  },
  {
    step: "04",
    title: "Generative AI",
    when: null,
    accent: "purple",
    icon: "sparkles",
    learned: "RAG, hybrid retrieval, multi-agent pipelines, LLM evaluation, guardrails",
    tools: ["Gemini", "OpenAI API", "LangChain", "CrewAI", "pgvector", "Whisper", "n8n"],
    built: [
      { label: "Haqqi", href: "/projects/haqqi" },
      { label: "Coverage Amplifier", href: "/projects/coverage-amplifier" },
    ],
  },
  {
    step: "05",
    title: "MLOps and deployment",
    when: null,
    accent: "pink",
    icon: "server",
    learned: "Experiment tracking, drift monitoring, containers, CI/CD, serverless",
    tools: ["MLflow", "Evidently", "Docker", "GitHub Actions", "FastAPI", "AWS", "Google Cloud Run"],
    built: [
      { label: "CardShield serving and monitoring", href: "/projects/cardshield" },
      { label: "Coverage Amplifier on Cloud Run", href: "/projects/coverage-amplifier" },
    ],
  },
  {
    step: "06",
    title: "Real-world experience",
    when: null,
    accent: "royal",
    icon: "briefcase",
    learned: "Owning systems from ambiguous requirements to production",
    tools: ["AWS Lambda", "Step Functions", "WhatsApp Business API"],
    built: [
      { label: "Ground Truth reporting platform", href: "#exp-ground-truth" },
      { label: "UrbanDart AI agent", href: "#exp-urbandart" },
    ],
  },
  {
    step: "Now",
    title: "Master of Applied Artificial Intelligence",
    when: "University of Wollongong in Dubai",
    accent: "white",
    icon: "graduation",
    learned: "",
    tools: [],
    built: [],
  },
];
